[package]
name = "rustcaptcha"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rustcaptcha"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
captcha = "*"
base64 = "0.13.0"
